services:
  fpm:
    environment:
      - PHP_VERSION=${PHP_VERSION}
    image: php:${PHP_VERSION}-fpm
    volumes:
      - ./php-fpm.conf:/usr/local/etc/php-fpm.d/zzzzz.conf:ro
      - php-socket:/var/run/php:rw
      - ./src:/var/www/html

  nginx:
    image: nginx:1.17
    volumes:
      - php-socket:/var/run/php
      - ./src:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 31337:80

volumes:
  php-socket: