services:
  cli:
    environment:
      - PHP_VERSION=${PHP_VERSION}
    image: php:${PHP_VERSION}-cli
    command: php -S 0.0.0.0:31337 -t /var/www/html
    volumes:
      - ./src:/var/www/html
    ports:
      - 31337:31337